services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_HOSTNAME_URL=http://localhost:8081
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - tp-network

  db:
    image: postgres:16
    container_name: postgres-db-contenedores
    restart: always
    environment:
      POSTGRES_DB: tp_contenedores
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tp-network
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  osrm:
    # Usamos la imagen de Docker Hub (v5.26.0 implícita) compatible con tus datos
    image: osrm/osrm-backend:latest
    container_name: osrm
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data:/data
    # Asegúrate de que este nombre coincida con el archivo que generaste en tu carpeta osrm-data
    command: osrm-routed /data/argentina-251129.osrm
    networks:
      - tp-network

  # MS-TRANSPORTE (ex ms-flota)
  ms-transporte:
    build:
      context: .
      dockerfile: ms-transporte/Dockerfile
    container_name: ms-transporte
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tp_contenedores
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8081/realms/tpi-backend
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/tpi-backend/protocol/openid-connect/certs
      # URLs de conexión
      MS_SOLICITUDES_URL: http://ms-solicitudes:8080
      MS_GEOLOCALIZACION_URL: http://ms-geolocalizacion:8080
    ports:
      - "8085:8080"
    expose:
      - "8080"
    networks:
      - tp-network

  # MS-GEOLOCALIZACION (ex ms-rutas)
  ms-geolocalizacion:
    build:
      context: .
      dockerfile: ms-geolocalizacion/Dockerfile
    container_name: ms-geolocalizacion
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      osrm:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tp_contenedores
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8081/realms/tpi-backend
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/tpi-backend/protocol/openid-connect/certs
      # URLs de conexión
      MS_TRANSPORTE_URL: http://ms-transporte:8080
      MS_SOLICITUDES_URL: http://ms-solicitudes:8080
      OSRM_API_URL: http://osrm:5000
    ports:
      - "8082:8080"
    expose:
      - "8080"
    networks:
      - tp-network

  # MS-SOLICITUDES (ex ms-seguimiento/solicitudes)
  ms-solicitudes:
    build:
      context: .
      dockerfile: ms-solicitudes/Dockerfile
    container_name: ms-solicitudes
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tp_contenedores
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8081/realms/tpi-backend
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/tpi-backend/protocol/openid-connect/certs
      # URLs de conexión
      MS_TRANSPORTE_URL: http://ms-transporte:8080
      MS_GEOLOCALIZACION_URL: http://ms-geolocalizacion:8080
    ports:
      - "8083:8080"
    expose:
      - "8080"
    networks:
      - tp-network

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: api-gateway
    restart: unless-stopped
    depends_on:
      ms-transporte:
        condition: service_started
      ms-geolocalizacion:
        condition: service_started
      ms-solicitudes:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:8081/realms/tpi-backend
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/tpi-backend/protocol/openid-connect/certs
      # URLs para el enrutamiento del gateway (coinciden con RouteConfig.java)
      - URI_SOLICITUDES=http://ms-solicitudes:8080
      - URI_GEOLOCALIZACION=http://ms-geolocalizacion:8080
      - URI_TRANSPORTE=http://ms-transporte:8080
    networks:
      - tp-network

volumes:
  postgres_data:
  keycloak_data:

networks:
  tp-network:
    driver: bridge